### ISSUE TITLE
Doesn't support redirects

### ISSUE THREAD

**Issue by aequasi** [Iridium/dev-server#1]
https://github.com/zeit/now-examples/tree/master/redirect

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Server.http.createServer (/app/node_modules/@iridium/dev-server/index.js:48:31)
    at Server.emit (events.js:180:13)
    at Server.emit (domain.js:422:20)
    at parserOnIncoming (_http_server.js:642:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)

```

**Comment by DavidBernal** [comment]
Fixed:
https://github.com/Iridium/dev-server/commit/0b08a1f488c9aac11b29faa68e8243281d7e570e
